### ISSUE TITLE
ArrayCollection->matching() not working anymore with Criteria->eq('id', $number)

### ISSUE THREAD

**Issue by Tagirijus** [doctrine/doctrine2#9109]
### Bug Report

|    Q        |   A
|------------ | ------
| BC Break    | yes
| Version     | 2.9.6

#### Summary

It seems that something changed with the `->matching()` method of an _ArrayCollection_. It persist in _v2.10.1_.

#### Current behavior

When I have an ArrayCollection I want to filter with `matching` and a Criteria, which has an expression like `->eq('id', $number)` my script tells me something like:

_"Could not resolve type of column "\`id\`" of class ..."_ and so on.

#### How to reproduce

Let's say you have an entity _"work"_ with an _ArrayCollection_ called _"connectedalbums"_, which stores other entities like _"album"_. I now want to access the _album_ with the id "3" and would do it like this:

```php
// $work is already fetched form the DB.

$criteria = new Criteria();
$criteria->where(Criteria::expr()->eq('id', 3));
$album = $work->getConnectedAlbums()->matching($criteria)->toArray();

if (!empty($album)) {
    $album = $album[0];
}
```

With this, PHP throws an _Uncaught RuntimeException_ like mentioned above.

#### Expected behavior

I expect an ArrayCollection with `->matching()` and the Criteria with the expression `->eq('id', $number)` to give me the correct item from the ArrayCollection, whichs column _id_ has the value, which is stored in _$number_. It worked like this in _v2.9.5_!

**Comment by armenio** [comment]
> ### Bug Report
> Q	A
> BC Break	yes
> Version	2.9.6
> #### Summary
> It seems that something changed with the `->matching()` method of an _ArrayCollection_. It persist in _v2.10.1_.
> 
> #### Current behavior
> When I have an ArrayCollection I want to filter with `matching` and a Criteria, which has an expression like `->eq('id', $number)` my script tells me something like:
> 
> _"Could not resolve type of column "`id`" of class ..."_ and so on.
> 
> #### How to reproduce
> Let's say you have an entity _"work"_ with an _ArrayCollection_ called _"connectedalbums"_, which stores other entities like _"album"_. I now want to access the _album_ with the id "3" and would do it like this:
> 
> ```
> // $work is already fetched form the DB.
> 
> $criteria = new Criteria();
> $criteria->where(Criteria::expr()->eq('id', 3));
> $album = $work->getConnectedAlbums()->matching($criteria)->toArray();
> 
> if (!empty($album)) {
>     $album = $album[0];
> }
> ```
> 
> With this, PHP throws an _Uncaught RuntimeException_ like mentioned above.
> 
> #### Expected behavior
> I expect an ArrayCollection with `->matching()` and the Criteria with the expression `->eq('id', $number)` to give me the correct item from the ArrayCollection, whichs column _id_ has the value, which is stored in _$number_. It worked like this in _v2.9.5_!

@Tagirijus try delete vendor folder and reinstall. Works here.

**Comment by Tagirijus** [comment]
Someone commented here and removed the comment again _(probably because it did not work for them neither)_, but I still tried the idea. The idea was to remove the _vendor_ folder and re-install with _composer_ again: it did not work here. Thanks for the idea, though!

**Comment by Nek-** [comment]
@greg0ire @Tagirijus isn't this fixed?

**Comment by Tagirijus** [comment]
As I wrote:  _"it persist in v2.10.1"_. (-;

**Comment by Nek-** [comment]
Hello, I tried a reproducer (in a symfony app, but still): https://gist.github.com/Nek-/b799f16acc1ff73833dd2f2a1d634848

It's working fine with Doctrine ORM 2.10.2.

**Comment by greg0ire** [comment]
@Nek- Hi mate! Is your gist missing a `docker-compose.yml`?

EDIT: ah no, it's just missing a `cd doctrine-matching-test`

And then the patch cannot be applied, because of how fast the ecosystem evolves: patching composer.lock won't work I'm afraid :p

**Comment by Nek-** [comment]
Fixed, nvm it just exposes that it's working fine and this issue should be closed to me 😉  .

**Comment by Tagirijus** [comment]
Well, sorry but it does still persist in _v2.10.2_ here. I also removed the vendor folder and did `composer install` again... did not help. )=

Edit: when I find some time, maybe I can dig deeper into this and try to understand on how to make some tests, in case my code example in my intitial post does not help. Sorry for not being able to give more information right now.

One information I found out, while I am not sure, if it is important: when downgrading again to work in _v2.9.5_ (since it works here), composer also shows that it is downgrading _doctrine/dbal v3.1.3_ to _v2.13.4_ and removes _symfony/polyfill-php72 v1.23.0_.

Oh an another info: I do not work with symfony at all. I use _Siler_ as a framework underneath ( https://github.com/leocavalcante/siler ).

**Comment by Nek-** [comment]
@Tagirijus please provide a reproducer. I took some personal time to try to reproduce and fix _your_ issue but instead I ended up showing that it's working fine.

**Comment by armenio** [comment]
I am using DoctrineOrmModule, running composer update doesn’t solve the problem

**Comment by armenio** [comment]
@Nek- @greg0ire @Tagirijus 
I really couldn't reproduce this in a test case.
**but I found the possible bug.**

It should be here: https://github.com/doctrine/orm/blob/2.10.x/lib/Doctrine/ORM/Persisters/Collection/ManyToManyPersister.php#L252

to contextualize, this happens before the bug:

```
[$name, $value, $operator] = $parameter;

$field = $this->quoteStrategy->getColumnName($name, $targetClass, $this->platform);
```
so here is the problem:

`$paramTypes[] = PersisterHelper::getTypeOfColumn($field, $targetClass, $this->em);`

**$field** needs to be replaced with **$name**

`$paramTypes[] = PersisterHelper::getTypeOfColumn($name, $targetClass, $this->em);`

Test results after that change:

```
Time: 01:15.521, Memory: 442.50 MB

OK, but incomplete, skipped, or risky tests!
Tests: 3600, Assertions: 13052, Skipped: 109, Incomplete: 2.
```

pay attention to merge with "weak" tests involving this: https://github.com/doctrine/orm/pull/9010

**Comment by Nek-** [comment]
@armenio without making a testcase to reproduce, can't you reproduce your issue in a standard app? (no matter the framework, just use yours to be the closest possible to your case).

**Comment by armenio** [comment]
@Nek- See: https://github.com/doctrine/orm/pull/9153

**Comment by armenio** [comment]
can you reopen?

**Comment by Tagirijus** [comment]
It would be okay **to me**, if this one only gets re-opened, when I finally come up with some clear reproducible tests, hehe. I do not find time for this at the moment, though. Sorry. ))=

**Comment by armenio** [comment]
> It would be okay **to me**, if this one only gets re-opened, when I finally come up with some clear reproducible tests, hehe. I do not find time for this at the moment, though. Sorry. ))=

I already created the test case forcing the error, see: https://github.com/doctrine/orm/pull/9153
@greg0ire @Nek- what else do i need to do?

**Comment by Tagirijus** [comment]
Could not test this either. But still thanks for your effort! (=

**Comment by armenio** [comment]
> Could not test this either. But still thanks for your effort! (=

what can i do to help even more?

**Comment by Tagirijus** [comment]
Get me some more free time so that I finally could test your posted test case on my own, haha. :D (-;

**Comment by greg0ire** [comment]
@armenio assuming this used to work in the past, you could use `git bisect` to find the commit that breaks your test.

**Comment by armenio** [comment]
> @armenio assuming this used to work in the past, you could use `git bisect` to find the commit that breaks your test.

@greg0ire I found!
What is the next step? I don't know the flow. please let me know what i need to know
here is the result of git bisect:
```
armenio@MacBook-Pro doctrine-orm % git bisect bad                                                                                                    
128ebe630b14e9db45efdede6b79847ba5920bdf is the first bad commit
commit 128ebe630b14e9db45efdede6b79847ba5920bdf
Author: Laszlo_Csupity <laszlo_csupity@epam.com>
Date:   Mon Sep 13 13:55:41 2021 +0200

    Use types in collection persister

 lib/Doctrine/ORM/Persisters/Collection/ManyToManyPersister.php | 5 ++++-
 1 file changed, 4 insertions(+), 1 deletion(-)
```

Screenshot:
![Screen Shot 2021-11-04 at 4 54 03 PM](https://user-images.githubusercontent.com/349304/140411360-b8946c24-fdfd-46bd-8e69-35a05d97d924.png)

**Comment by greg0ire** [comment]
Next steps:
- find that commit on Github;
- find the pull request (appears on the commit page);
- let the author know about this issue.

**Comment by armenio** [comment]
> Next steps:
> 
> * find that commit on Github;
> * find the pull request (appears on the commit page);
> * let the author know about this issue.

Thanks @greg0ire! Just reported at https://github.com/doctrine/orm/pull/9010

**Comment by greg0ire** [comment]
> pay attention to merge with "weak" tests involving this: #9010

Oh wow hold on a minute… do you mean to say you would have spotted the issue had you reviewed that PR?

**Comment by armenio** [comment]
> > pay attention to merge with "weak" tests involving this: #9010
> 
> Oh wow hold on a minute… do you mean to say you would have spotted the issue had you reviewed that PR?

Maybe, why not? I did this to get your attention that there really is something wrong there.
I have the bug "apparently" fixed here locally. 
Can I push it in my PR https://github.com/doctrine/orm/pull/9153 for you to review?
Thanks!

**Comment by greg0ire** [comment]
> Can I push it in my PR #9153 for you to review?

What would be the point? You've demonstrated that I'm not good enough to review a PR.
Jokes aside, you can push the fix, but I personally won't be participating in this unless a sincere apology comes first.

**Comment by armenio** [comment]
> What would be the point? You've demonstrated that I'm not good enough to review a PR. Jokes aside, you can push the fix, but I personally won't be participating in this unless a sincere apology comes first.

Please don't get me wrong. maybe it's because of my bad English. See the quotes in the word.
As I said, I tried to get your attention for the situation. I didn't necessarily mean you, of course.
Anyway, I sincerely apologize. Mainly for seeming rude.
I will push the attempt to fix. If you can, please review it when you can.
I thank you again

**Comment by greg0ire** [comment]
Not super convincing, but in doubt, I'll accept the apology and give this PR a review.
